version: '3'

services:
  rag-api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./indexes:/app/indexes
    env_file:
      - .env
    environment:
      - DATABASE_URL=postgresql+psycopg2://postgres@db:5432/postgres
    depends_on:
      - db
    deploy:
      resources:
        limits:
          memory: 16G
    restart: unless-stopped

  db:
    image: postgres:15
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: 