"""Add query processing settings

Revision ID: 2bcf2be1a1f6
Revises: 
Create Date: 2025-05-10 10:42:50.257805

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '2bcf2be1a1f6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('documents', 'processing_params',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               type_=sa.JSON(),
               existing_nullable=True)
    op.add_column('model_configs', sa.Column('use_query_processing', sa.Boolean(), nullable=True))
    op.add_column('model_configs', sa.Column('use_query_rephrase', sa.Boolean(), nullable=True))
    op.add_column('model_configs', sa.Column('use_chain_of_thought', sa.Boolean(), nullable=True))
    op.drop_index('ix_model_configs_id', table_name='model_configs')
    op.create_unique_constraint(None, 'model_configs', ['user_id'])
    op.drop_constraint('model_configs_user_id_fkey', 'model_configs', type_='foreignkey')
    op.create_foreign_key(None, 'model_configs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('model_configs', 'top_p')
    op.drop_column('model_configs', 'top_k_chunks')
    op.drop_column('model_configs', 'context_window')
    op.add_column('users', sa.Column('email', sa.String(), nullable=True))
    op.add_column('users', sa.Column('is_active', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'is_active')
    op.drop_column('users', 'email')
    op.add_column('model_configs', sa.Column('context_window', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('model_configs', sa.Column('top_k_chunks', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('model_configs', sa.Column('top_p', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'model_configs', type_='foreignkey')
    op.create_foreign_key('model_configs_user_id_fkey', 'model_configs', 'users', ['user_id'], ['id'])
    op.drop_constraint(None, 'model_configs', type_='unique')
    op.create_index('ix_model_configs_id', 'model_configs', ['id'], unique=False)
    op.drop_column('model_configs', 'use_chain_of_thought')
    op.drop_column('model_configs', 'use_query_rephrase')
    op.drop_column('model_configs', 'use_query_processing')
    op.alter_column('documents', 'processing_params',
               existing_type=sa.JSON(),
               type_=postgresql.JSONB(astext_type=sa.Text()),
               existing_nullable=True)
    # ### end Alembic commands ### 