"""Change default temperature to 0

Revision ID: bfe17de1de3f
Revises: 2bcf2be1a1f6
Create Date: 2025-05-10 10:48:12.484788

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bfe17de1de3f'
down_revision = '2bcf2be1a1f6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 